// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJUzIbH-5e5SOKf9cEzCJExJ4ZNKDXy9s',
    appId: '1:587549584096:web:bee62d48db443e0414fe85',
    messagingSenderId: '587549584096',
    projectId: 'sell-application',
    authDomain: 'sell-application.firebaseapp.com',
    storageBucket: 'sell-application.appspot.com',
    measurementId: 'G-BTNBM616TT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBtHu5D0RhAijPK7IQzYRtcP1vHIv_Olk',
    appId: '1:587549584096:android:7e8bfeb74e5b128714fe85',
    messagingSenderId: '587549584096',
    projectId: 'sell-application',
    storageBucket: 'sell-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHIGHo2W6FfA05TfzhpPXN4ktSN2oEy3E',
    appId: '1:587549584096:ios:94fe625bbb1bb21d14fe85',
    messagingSenderId: '587549584096',
    projectId: 'sell-application',
    storageBucket: 'sell-application.appspot.com',
    iosClientId: '587549584096-3it2ih12uq1fi78h3r0dav1ahdel0jbk.apps.googleusercontent.com',
    iosBundleId: 'com.example.sellApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHIGHo2W6FfA05TfzhpPXN4ktSN2oEy3E',
    appId: '1:587549584096:ios:94fe625bbb1bb21d14fe85',
    messagingSenderId: '587549584096',
    projectId: 'sell-application',
    storageBucket: 'sell-application.appspot.com',
    iosClientId: '587549584096-3it2ih12uq1fi78h3r0dav1ahdel0jbk.apps.googleusercontent.com',
    iosBundleId: 'com.example.sellApp',
  );
}
